services:
  postgres:
    container_name: postgres
    image: library/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-keycloak}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-keycloak}
      POSTGRES_DB: keycloak_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  keycloak:
    image: keycloak/keycloak:25.0.4
    container_name: keycloak
    command:
      - start-dev
    environment:
      KC_HOSTNAME: "http://localhost:8080"
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: ${POSTGRES_USER:-keycloak}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-keycloak}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
