services:
  postgres:
    container_name: postgres
    image: postgres:17.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-keycloak}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-keycloak}
      POSTGRES_DB: keycloak_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  keycloak:
    image: keycloak/keycloak:26.2.3
    container_name: keycloak
    command:
      - start
    environment:
      KC_HOSTNAME: "https://localhost:9000/custom"
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: ${POSTGRES_USER:-keycloak}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-keycloak}
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: true

  proxy:
    image: nginx:1.27.5
    container_name: proxy
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./self.crt:/etc/ssl/self.crt:ro
      - ./self.key:/etc/ssl/self.key:ro
